import './Privacy.css'
export default function Privacy() {
return (
<section className="policy-wrap">
      <h1 className="policy-title">Privacy Policy</h1>

      <div className="policy-updated">
        Last updated: Feb 07, 2023
      </div>

      <div className="policy-block">
        <p className="policy-text">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about your privacy rights and how the law
          protects You.
        </p>

        <p className="policy-text">
          We use Your Personal data to provide and improve the Service. By
          using the Service, You agree to the collection and use of information
          in accordance with this Privacy Policy.
        </p>
      </div>

      <h2 className="policy-heading">
        Interpretation and Definitions
      </h2>

      <h3 className="policy-subheading">Interpretation</h3>

      <div className="policy-block">
        <p className="policy-text">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
      </div>

      <h3 className="policy-subheading">Definitions</h3>

      <div className="policy-block">
        <p className="policy-text">
          For the purposes of this Privacy Policy:
        </p>

        <p className="policy-text">
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </p>

        <p className="policy-text">
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us" or "Our" in this Agreement) refers to Trend Electronics Limited.
        </p>

        <p className="policy-text">
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </p>

        <p className="policy-text">
          <strong>Country</strong> refers to: India
        </p>

        <p className="policy-text">
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone or a digital tablet.
        </p>

        <p className="policy-text">
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </p>

        <p className="policy-text">
          <strong>Service</strong> refers to the Website.
        </p>

        <p className="policy-text">
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service or to assist the
          Company in analyzing how the Service is used.
        </p>

        <p className="policy-text">
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself.
        </p>

        <p className="policy-text">
          <strong>Website</strong> refers to www.trendelectronics.in,
          accessible from www.trendelectronics.in
        </p>

        <p className="policy-text">
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which
          such individual is accessing or using the Service, as applicable.
        </p>
      </div>

      <h2 className="policy-heading">
        Collecting and Using Your Personal Data
      </h2>

      <h3 className="policy-subheading">Types of Data Collected</h3>

      <h3 className="policy-subheading">Personal Data</h3>

      <div className="policy-block">
        <p className="policy-text">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>

        <p className="policy-text">Email address</p>
        <p className="policy-text">First name and last name</p>
        <p className="policy-text">Phone number</p>
        <p className="policy-text">Product / Service Interested</p>
      </div>

      <h3 className="policy-subheading">Use of Your Personal Data</h3>

      <div className="policy-block">
        <p className="policy-text">
          The Company may use Personal Data for the following purposes:
        </p>

        <p className="policy-text">
          To provide and maintain our Service, including to monitor the usage
          of our Service.
        </p>

        <p className="policy-text">
          To manage Your Account: to manage Your registration as a user of the
          Service. The Personal Data You provide can give You access to
          different functionalities of the Service that are available to You
          as a registered user.
        </p>

        <p className="policy-text">
          For the performance of a contract: the development, compliance and
          undertaking of the purchase contract for the products, items or
          services You have purchased or of any other contract with Us through
          the Service.
        </p>

        <p className="policy-text">
          To contact You: To contact You by email, telephone calls, SMS, or
          other equivalent forms of electronic communication.
        </p>

        <p className="policy-text">
          To provide You with news, special offers and general information
          about other goods, services and events which we offer.
        </p>

        <p className="policy-text">
          To manage Your requests: To attend and manage Your requests to Us.
        </p>

        <p className="policy-text">
          For business transfers: We may use Your information to evaluate or
          conduct a merger, divestiture, restructuring, reorganization,
          dissolution, or other sale or transfer of some or all of Our assets.
        </p>

        <p className="policy-text">
          For other purposes: We may use Your information for other purposes,
          such as data analysis, identifying usage trends, determining the
          effectiveness of our promotional campaigns and to evaluate and
          improve our Service.
        </p>
      </div>

      <h3 className="policy-subheading">Sharing of Personal Data</h3>

      <div className="policy-block">
        <p className="policy-text">
          We may share Your personal information in the following situations:
        </p>

        <p className="policy-text">
          With Service Providers: We may share Your personal information with
          Service Providers to monitor and analyze the use of our Service.
        </p>

        <p className="policy-text">
          For business transfers: We may share or transfer Your personal
          information in connection with any merger, sale of Company assets,
          financing, or acquisition.
        </p>

        <p className="policy-text">
          With Affiliates: We may share Your information with Our affiliates.
        </p>

        <p className="policy-text">
          With business partners: We may share Your information with Our
          business partners to offer You certain products, services or
          promotions.
        </p>

        <p className="policy-text">
          With other users: when You share personal information or otherwise
          interact in the public areas with other users.
        </p>

        <p className="policy-text">
          With Your consent: We may disclose Your personal information for any
          other purpose with Your consent.
        </p>
      </div>

      <h2 className="policy-heading">
        Retention of Your Personal Data
      </h2>

      <div className="policy-block">
        <p className="policy-text">
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy.
        </p>

        <p className="policy-text">
          The Company will also retain Usage Data for internal analysis
          purposes.
        </p>
      </div>

      <h2 className="policy-heading">
        Transfer of Your Personal Data
      </h2>

      <div className="policy-block">
        <p className="policy-text">
          Your information, including Personal Data, is processed at the
          Company's operating offices and in any other places where the parties
          involved in the processing are located.
        </p>

        <p className="policy-text">
          Your consent to this Privacy Policy followed by Your submission of
          such information represents Your agreement to that transfer.
        </p>

        <p className="policy-text">
          The Company will take all steps reasonably necessary to ensure that
          Your data is treated securely and in accordance with this Privacy
          Policy.
        </p>
      </div>

      <h2 className="policy-heading">
        Disclosure of Your Personal Data
      </h2>

      <h3 className="policy-subheading">Business Transactions</h3>

      <div className="policy-block">
        <p className="policy-text">
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred.
        </p>
      </div>

      <h3 className="policy-subheading">Law enforcement</h3>

      <div className="policy-block">
        <p className="policy-text">
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law.
        </p>
      </div>

      <h3 className="policy-subheading">
        Other legal requirements
      </h3>

      <div className="policy-block">
        <p className="policy-text">
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to:
        </p>

        <p className="policy-text">
          Comply with a legal obligation
        </p>

        <p className="policy-text">
          Protect and defend the rights or property of the Company
        </p>

        <p className="policy-text">
          Prevent or investigate possible wrongdoing in connection with the
          Service
        </p>

        <p className="policy-text">
          Protect the personal safety of Users of the Service or the public
        </p>

        <p className="policy-text">
          Protect against legal liability
        </p>
      </div>

      <h2 className="policy-heading">
        Security of Your Personal Data
      </h2>

      <div className="policy-block">
        <p className="policy-text">
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure.
        </p>
      </div>

      <h2 className="policy-heading">
        Children's Privacy
      </h2>

      <div className="policy-block">
        <p className="policy-text">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13.
        </p>

        <p className="policy-text">
          If We need to rely on consent as a legal basis for processing Your
          information and Your country requires consent from a parent, We may
          require Your parent's consent.
        </p>
      </div>

      <h2 className="policy-heading">
        Links to Other Websites
      </h2>

      <div className="policy-block">
        <p className="policy-text">
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party's site.
        </p>

        <p className="policy-text">
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
      </div>

      <h2 className="policy-heading">
        Changes to this Privacy Policy
      </h2>

      <div className="policy-block">
        <p className="policy-text">
          We may update Our Privacy Policy from time to time. We will notify
          You of any changes by posting the new Privacy Policy on this page.
        </p>

        <p className="policy-text">
          We will let You know via email and/or a prominent notice on Our
          Service, prior to the change becoming effective.
        </p>

        <p className="policy-text">
          You are advised to review this Privacy Policy periodically for any
          changes.
        </p>
      </div>

      <h2 className="policy-heading">Contact Us</h2>

      <div className="policy-block">
        <p className="policy-text">
          If you have any questions about this Privacy Policy, You can contact
          us: <strong>By email: 
            info@trendelectronics.in
            </strong>
        </p>
      </div>

    </section>
  
);
}
